// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClwBeC06EOay3SX_PzLMIOItzMKzwiyPo',
    appId: '1:991350024629:web:4adf29fdfe2e28c5ed11fc',
    messagingSenderId: '991350024629',
    projectId: 'todo-application-c4308',
    authDomain: 'todo-application-c4308.firebaseapp.com',
    storageBucket: 'todo-application-c4308.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh4ygzOao6mmY0mwDsrJYGU37_7yGZv4Q',
    appId: '1:991350024629:android:83159c01534b9cc1ed11fc',
    messagingSenderId: '991350024629',
    projectId: 'todo-application-c4308',
    storageBucket: 'todo-application-c4308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVucr461q1wkPZZWfX1BCt9foLACFWj1M',
    appId: '1:991350024629:ios:2b61f573088cb8f8ed11fc',
    messagingSenderId: '991350024629',
    projectId: 'todo-application-c4308',
    storageBucket: 'todo-application-c4308.appspot.com',
    iosClientId: '991350024629-ovn55v7f3ogm7a6pkcl279msd1018k4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVucr461q1wkPZZWfX1BCt9foLACFWj1M',
    appId: '1:991350024629:ios:2b61f573088cb8f8ed11fc',
    messagingSenderId: '991350024629',
    projectId: 'todo-application-c4308',
    storageBucket: 'todo-application-c4308.appspot.com',
    iosClientId: '991350024629-ovn55v7f3ogm7a6pkcl279msd1018k4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApplication',
  );
}
